### ISSUE TITLE
return-license fails to return a license

### ISSUE THREAD

**Issue by oshaughnessy** [game-ci/unity-return-license#20]
**Bug description**

Running "return-license" does not return a license. 

**How to reproduce**

Manually invoke this workflow definition:

```
jobs:
  return-license:
    runs-on: ${{ github.event.inputs.runs-on }}
    env:
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
    steps:
      - uses: game-ci/unity-return-license@main
        if: always()
```

**Expected behavior**

An allocation of the license associated with `$UNITY_SERIAL` is returned to the Unity ID service.

**Additional details**

```
Initiating legacy licensing module
DisplayProgressbar: Returning license
Cancelling DisplayDialog: Failed to return license Unity license return request has timed out. Please verify that you are connected to the Internet and/or try again later.
This should not be called in batch mode.
 
(Filename: ./Editor/Platform/Linux/EditorUtility.cpp Line: 274)

DisplayProgressbar: Unity license
[UnityConnectServicesConfig] config is NOT valid, switching to default
[0322/193048:ERROR:browser_main_loop.cc(161)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[0322/193048:ERROR:sandbox_linux.cc(308)] InitializeSandbox() called with multiple threads in process gpu-process
Cancelling DisplayDialog: Failed to activate/update license. Missing or bad username and password. Please try again using valid credentials or contact support@unity3d.com
This should not be called in batch mode.
 
(Filename: ./Editor/Platform/Linux/EditorUtility.cpp Line: 274)
```
